name: api.env.cicd
on:

  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment'
      default: false
      required: true
      type: boolean
env:

  env_var: ${{ vars.ENV_CONTEXT_VAR }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Test'
    steps:
    - uses: actions/checkout@v2

    - name: Use variables
      run: |
        echo "repository variable : $FOO"


